.PHONY: setup dev lint format test migrate migrate-new down

setup: ## Create .venv and install all deps (incl. dev group)
	uv sync

dev: ## Run local dev server with reload
	uv run fastapi dev app/main.py

lint: ## Static checks: ruff (lint) + ruff (format --check) + mypy
	uv run ruff check .
	uv run ruff format --check .
	uv run mypy app

format: ## Auto-format and auto-fix with ruff
	uv run ruff check --fix .
	uv run ruff format .

test: ## Run test suite with coverage
	uv run pytest

migrate: ## Apply DB migrations
	uv run alembic upgrade head

migrate-new: ## Create a new autogenerated migration (usage: make migrate-new msg="add tasks table")
	uv run alembic revision --autogenerate -m "$(msg)"

down: ## Stop the local docker compose stack
	docker compose down
