.PHONY: setup dev lint format test migrate migrate-new env local-run down hooks-install hooks-run

setup: ## Create .venv and install all deps (incl. dev group)
	uv sync

hooks-install: ## Install pre-commit + pre-push git hooks
	uv run pre-commit install --hook-type pre-commit --hook-type pre-push

hooks-run: ## Run all pre-commit hooks against the full repo
	uv run pre-commit run --all-files

dev: ## Run local dev server with reload
	uv run fastapi dev app/main.py

lint: ## Static checks: ruff (lint) + ruff (format --check) + mypy
	uv run ruff check .
	uv run ruff format --check .
	uv run mypy app

format: ## Auto-format and auto-fix with ruff
	uv run ruff check --fix .
	uv run ruff format .

test: ## Run test suite with coverage
	uv run pytest

migrate: ## Apply DB migrations
	uv run alembic upgrade head

migrate-new: ## Create a new autogenerated migration (usage: make migrate-new msg="add tasks table")
	uv run alembic revision --autogenerate -m "$(msg)"

env: ## Create .env from .env.example with freshly generated secrets (no-op if .env already exists)
	@bash scripts/generate_env.sh

local-run: env ## Generate .env if needed, then build and start the full docker compose stack
	docker compose up --build

down: ## Stop the local docker compose stack
	docker compose down
