"""add deleted_at to tasks and task_lists

Revision ID: 4d53b31b3e64
Revises: 171357d9e368
Create Date: 2026-09-20 16:59:42.951667

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4d53b31b3e64"
down_revision: str | None = "171357d9e368"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invitations", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("task_lists", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("tasks", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "deleted_at")
    op.drop_column("task_lists", "deleted_at")
    op.drop_column("invitations", "deleted_at")
    # ### end Alembic commands ###
