"""partial unique index for active invitations

Revision ID: 846cc0402bf6
Revises: 4d53b31b3e64
Create Date: 2026-09-20 19:09:09.791782

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "846cc0402bf6"
down_revision: str | None = "4d53b31b3e64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_invitations_list_id_email"), "invitations", type_="unique")
    op.create_index(
        "uq_invitations_list_id_email_active",
        "invitations",
        ["list_id", "email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_invitations_list_id_email_active",
        table_name="invitations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_invitations_list_id_email"),
        "invitations",
        ["list_id", "email"],
    )
    # ### end Alembic commands ###
