"""add priority to tasks

Revision ID: c3deb8346827
Revises: d323b1b1822e
Create Date: 2026-09-18 23:32:45.736250

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c3deb8346827"
down_revision: str | None = "d323b1b1822e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="taskpriority", native_enum=False, length=20),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "priority")
    # ### end Alembic commands ###
